#!/bin/bash

SWITCHER=switcher
HOST=localhost
PORT=1234
#run gui by default
UI=gui

FILE1=/tmp/sw1-$$
FILE2=/tmp/sw2-$$
ERROR=/tmp/sw-err-$$

GETTEXT="gettext -d switcher_ui"

if [ -r ~/.switcher.conf ]
then
	. ~/.switcher.conf
elif [ -r /etc/switcher.conf ]
then
	. /etc/switcher.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

help () {
	echo "Usage: $0 [ host [port] | --help | --tui ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

show_dialog () {
	$DIALOG --title "Switching between unencrypted and QKD encrypted channels" \
			--menu "`$GETTEXT \"Switch to:\"`" 10 60 2 1 Unencrypted\ Channel 2 Quantum\ Channel\ \(QKD\) 2> $FILE1 || end
	if cat $FILE1 | $SWITCHER > $FILE2 2> $ERROR
	then
		MSG="`$GETTEXT \"Result:\"` `cat $FILE2`\\n\\n`$GETTEXT \"Switch channel again?\"`"
		$DIALOG --title "Result" --yesno "$MSG" 10 40 || end
	else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Switch channel again?\"`"
		$DIALOG --title "Error" --yesno "$MSG" 10 40 || end
	fi
}

show_tui () {
	echo "Choose the channel you want to switch: 1 or 2. Type q to quit."
	echo "1 - Unencrypted Channel"
	echo "2 - Quantum Channel (QKD)"
	read CHOICE
	if [ $CHOICE -eq 1 -o $CHOICE -eq 2 ]
	then
		echo $CHOICE > $FILE1
		if cat $FILE1 | $SWITCHER > $FILE2 2> $ERROR
		then
			echo "Result: `cat $FILE2`" || end
		else
			echo "Error: `cat $ERROR`" || end
		fi
	elif [ "$CHOICE" = 'q' ]
	then
		end
		exit
	else
		echo "Wrong input!!! Please try again..."
	fi
}

if [ $# -eq 1 ]
then
    if [ "$1" = '--help' ]
    then
        help
        exit 1
    elif [ "$1" = '--tui' ]
    then
		UI="tui"
    else
        HOST=$1
    fi
elif [ $# -eq 2 ]
then
    PORT=$2
fi

if [ $# -ge 1 -o `basename $0` = 'nswitcher_ui' ]
then
	if [ $HOST -a $PORT ]
	then
        SWITCHER="nc $HOST $PORT"
	else
		echo "You must set HOST and PORT"
		exit 2
	fi
fi

while true
do
	if [ $UI = 'tui' ]
	then
		show_tui
	else
		show_dialog
	fi
done
