#!/bin/sh
FILE=/tmp/sw-$$

read CHNL
#send request to switch channel
echo "curl -X GET http://localhost:8080/channel/1/$CHNL | jq -r '.result'" > $FILE
sh $FILE

EXIT_STATUS=$?
rm -f $FILE
exit $EXIT_STATUS
